### ISSUE TITLE
Support base_url for client

### ISSUE THREAD

**Issue by bdqfork** [getmetal/motorhead#100]
Can you please support me in modifying the `base_url` as I am currently using some OpenAI-like services?

**Comment by Czechh** [comment]
we're using async-openai for out client, and it seems like they support setting api_base https://docs.rs/async-openai/latest/async_openai/config/struct.OpenAIConfig.html#method.with_api_base

Is this what you're looking for? setting this as an env variable to overwrite that default api base?

**Comment by bdqfork** [comment]
> we're using async-openai for out client, and it seems like they support setting api_base https://docs.rs/async-openai/latest/async_openai/config/struct.OpenAIConfig.html#method.with_api_base
> 
> Is this what you're looking for? setting this as an env variable to overwrite that default api base?

Yes, I want to set this as an env variable to overwrite that default api base.

**Comment by kranthi419** [comment]
@bdqfork  https://github.com/getmetal/motorhead/pull/102 please vote this pr.
