### ISSUE TITLE
How to initialize a conversation with a provided context and messages?

### ISSUE THREAD

**Issue by soylomass** [getmetal/motorhead#22]
What if I want to load an existing conversation into motorhead, and want to give it only the last N messages and the previously generated summarized context? Is there a way to do this?

More context: I have the user conversations and messages stored in a relational database. I want users to be able to load old conversations and continue them. I'd like to load the conversations to motorhead when the chat session starts, and remove them from motorhead when it ends, storing the last motorhead generated summary to the db when that happens.

**Comment by Czechh** [comment]
With https://github.com/getmetal/motorhead/pull/25 - you can now provide `context` in the POST request.

In your case the flow could be:
- Load initial state using `POST /sessions/:id/memory` => `{ messages, context }`.
- Keep running the chat session, allow for incremental summarization.
- When done `DELETE /sessions/:id/memory`

Let me know if that flow makes sense @soylomass - and thanks for the issue.
