### ISSUE TITLE
Messages summarized in wrong order

### ISSUE THREAD

**Issue by soylomass** [getmetal/motorhead#23]
Messages are passed in the wrong order to the summarizer. Example:

> messages_joined: AI: If you have any questions or if there's anything else you'd like to talk about, feel free to let me know!
> Human: no
> AI: Alright then. If you have any questions or if there's anything else you'd like to talk about, feel free to let me know!
> Human: no
> AI: Is there something that you would like to ask me or discuss? I'm here to help in whatever way I can.
> Human: no
> AI: Hello! How can I assist you today?

In this example, the last one was the first message.

In many circumstances, this doesn't matter, but sometimes it does. In a similar conversation, the summary returned:

> The human initially rejects the AI's offer of assistance, but the AI persists in asking how it can help. The human eventually greets the AI, to which the AI responds with an inquiry...

This summary is wrong, as the human didn't "finally greet", but started the conversation greeting.

**Comment by soylomass** [comment]
Seems that the messages are put into the prompt in the wrong order when using langchainjs and the motorhead memory too. Can anyone confirm?
PS: I'm using returnMessages: true mode

**Comment by Czechh** [comment]
@soylomass confirmed, working on a fix for the summarizer portion.

**Comment by Czechh** [comment]
Thank you for the issue! Should be fixed now 🤘
