### ISSUE TITLE
Erro deploying this container

### ISSUE THREAD

**Issue by ade5791** [getmetal/motorhead#39]
[2023-04-24T02:25:18Z INFO  motorhead] Starting Motörhead 🤘
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: can't connect with TLS, the feature is not enabled', src/main.rs:30:48
stack backtrace:

**Comment by ade5791** [comment]
This is the error log from railway

**Comment by Czechh** [comment]
Do you have it connected to a redis instance with `redisearch` ? I'm curious if you got that to work first.

**Comment by ade5791** [comment]
How do you go about connecting to redisearch. I have it connected to the redis provided by Railway and I have also tried the redis from Heroku.

**Comment by ade5791** [comment]
Okay, after setting up the Redis search what info do I need from redis search to set up Motorhead in Railway? the URL, username, and Password?

**Comment by Czechh** [comment]
yes

**Comment by ade5791** [comment]
![image](https://user-images.githubusercontent.com/38266156/234710845-0f9438a8-4490-48c5-8491-58269dccce08.png)

**Comment by ade5791** [comment]
using these credentials from redis search and still the deployment is failing in Railway. Could we connect via discord to discuss this?

**Comment by ade5791** [comment]
getting this error. note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-04-26T21:55:26Z INFO  motorhead] Starting Motörhead 🤘
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Redis URL did not parse', src/main.rs:30:48
stack backtrace:
0: rust_begin_unwind
at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5

**Comment by ade5791** [comment]
![image](https://user-images.githubusercontent.com/38266156/234718976-f7bb3a2c-8c98-412d-9972-8bdeb3967d2a.png)
 I was able to enter the correct redis URL but then I am not seeing any indication that the motorhead is running.

**Comment by Czechh** [comment]
@ade5791 happy to connect on discord. Feel free to ping me! It looks like it's working!
