### ISSUE TITLE
Chat history return reversed order

### ISSUE THREAD

**Issue by BankNatchapol** [getmetal/motorhead#51]
```
memory = MotorheadMemory(
    session_id="testing-1",
    url="http://localhost:8080",
    memory_key="chat_history"
)
asyncio.run(memory.init())  # loads previous state from Motörhead 
for m in memory.chat_memory.messages:
    print(m)
context = ""
if memory.context:
    context = f"\nPrevious context: {memory.context}"

template = "You are a chatbot having a conversation with a human."\
            f"""{context}\n"""\
            "{chat_history}\n"\
            "Human: {human_input}\n"\
            "AI:"

prompt = PromptTemplate(
    input_variables=["chat_history", "human_input"], 
    template=template
)
llm_chain = LLMChain(
    llm=ChatOpenAI(), 
    prompt=prompt, 
    verbose=True, 
    memory=memory
)
```

I'm following this python example and found that somehow chat_history comes in reversed order.
In this output it should be Human: 1 AI... Human: 2 AI ...

You are a chatbot having a conversation with a human.
AI: I'm sorry, I'm still not sure what you're trying to communicate. Can you please provide more context or information?
Human: 3
AI: I'm sorry, I'm not sure what you mean by "1" and "2". Could you please clarify your request or question?
Human: 2
AI: Hello, how can I assist you today?
Human: 3
AI: I'm sorry, I'm not sure what you mean by "1" and "2". Could you please clarify your request or question?
Human: 2
AI: Hello, how can I assist you today?
Human: 1
Human: 4
AI:

**Comment by Czechh** [comment]
hey @BankNatchapol just confirming that this is not an issue? There was an old bug before where this was happening.

**Comment by BankNatchapol** [comment]
> hey @BankNatchapol just confirming that this is not an issue? There was an old bug before where this was happening.

I just realize that this must be the LangChain lib problem.
Maybe because motorhead part in langchain havent updated yet, so i opened an issue there instead. 
Sorry, for no description here.🙏
