### ISSUE TITLE
More details on why long-term doesn't work with Azure deployment

### ISSUE THREAD

**Issue by tuanalumi** [getmetal/motorhead#78]
I see this note in readme
> NOTE: `MOTORHEAD_LONG_TERM_MEMORY=true` won't work with Azure. 

But it's unclear to me if the long-term feature doesn't work at all, or just the `MOTORHEAD_LONG_TERM_MEMORY` config. And why is that so?

The way I understand this, is that long-term memory uses Redisearch VSS to store the chat history. So it's just the matter of whether the Redis instance has Redisearch feature available. What do I miss here?

**Comment by Czechh** [comment]
Hey @tuanalumi  - thanks for bringing this up.

At the time, I wasn't sure if you could have both an LLM and an embedding model in a single Azure deployment. It looks like that is the case? Can you confirm, please.

We can adapt to allow this, just need to make sure that the azure client gets used for the embedding generation.

**Comment by Czechh** [comment]
Thank you @daviddahl - we'll get to this this week, otherwise PRs welcome!

**Comment by paulpierre** [comment]
Hi was this resolved?

**Comment by shubham184** [comment]
+

**Comment by Czechh** [comment]
I see that the code is there to generate the embeddings using azure as well, so I think that note might've been more of a warning on my end. Has anyone tested this? I think it might just work.

**Comment by Czechh** [comment]
I just added `AZURE_DEPLOYMENT_ID_ADA` to fix this. Will release soon, it will be a breaking change though
